import { useState } from 'react';

import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';


export default function Home() {

  const [textValue, setTextValue] = useState("")
  const [allTodos, setAllTodos] = useState([])

  const onTodoTextChange = (event) => {
    setTextValue(event.target.value)
  }

  const onAddTodoClick = () => {
   const newAllTodoList = [...allTodos, textValue]
   console.log(newAllTodoList)
   setAllTodos(newAllTodoList)
  }

  const submitHandler = (event) => {
    event.preventDefault()
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page}`}
      >
        <main className={styles.main}>
          <form
            onSubmit={submitHandler}
          >
            <Container
              maxWidth="md"
              component="main"
              sx={{ mt: 10 }}
            >
              <Grid container spacing={2}>

                <Grid size={10}>
                 <TextField
                  variant="outlined"
                  label="Todo Item"
                  fullWidth
                  sx={{
                    contrastText: "blue"
                  }}
                  onChange={onTodoTextChange}
                  value={textValue}
                 >
                 </TextField>
                </Grid>

                <Grid size={2}>
                  <Button
                    type="submit"
                    variant="contained"
                    size="large"
                    onClick={onAddTodoClick}
                  >
                  Add Todo Item
                  </Button>
                </Grid>

              </Grid>
            </Container>
          </form>
        </main>
      </div>
    </>
  );
}
